### PR TITLE
Remove LTL currency and replace with EUR for Lithuania

### PR DESCRIPTION
**Pull request by lscown**
fixes: https://github.com/pocketsmith/pocketsmith/issues/2835

I'm actually not sure how we test this - but I'm sure if the changes are all good, should be fine.

Also, it seems there's no editor config, so my sublime has stripped leading spaces, and for some reason replaced new lines with new lines. Dunno. Perhaps a tab thing? 

Will clean up if need be 👍

### CODE REVIEW

**Comment by wigsgiw** [comment]
LTL is still a valid currency, as EUR was only switched to fairly recently.

So I think that perhaps all we should be changing is the currency map maybe, will be worth looking at recent similar PRs.

Update: there are no previous examples... let's discuss this further over in Slack I think.

**Comment by maknz** [comment]
Yeah, the currencies definition file is all good as it is, we just need to start detecting EUR as the base currently for LT users. So yeah, just that countries file I recks.

In fact, we should probably go to the main repo https://github.com/beatrichartz/exchange and grab whatever their country map is, as it could have other changes we need too.

**Comment by lscown** [comment]
Sweet, copied over the new country code mapping. There is a number of changes here, but nothing diff'd in the currency definitions, which would mean this is all kosher

**Comment by 6twenty** [comment]
Looks like this has been merged into the new repo (https://github.com/pocketsmith/exchange)

**Pull request closed without merging**
